name: build

on:
  push:
    branches:
    - master
    - development

defaults:
  run:
    shell: bash

env:
  GO_VERSION: 1.14

jobs:
  build:
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{env.GO_VERSION}}

    - name: Build
      run: go build -o ./backend ./cmd/backend

    - name: Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wartemis/backend
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
